<a href="https://colab.research.google.com/github/Neelanjana000/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy


###Less Memory

In [ ]:
import numpy as np
import time
import sys

l=range(1000)
print(sys.getsizeof(5)*len(l))

array=np.arange(1000)
print(array.size*array.itemsize)

28000
8000


###Fast and Convinient

In [ ]:
Size =100000000
l1=range(Size)
l2=range(Size)

a1=np.arange(Size)
a2=np.arange(Size)

#Python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
#Numpy array
start = time.time()
result = a1+a2
print("numpy took: ",(time.time()-start)*1000)

python list took:  14092.2269821167
numpy took:  485.34607887268066


##Basic Array Operations

In [ ]:
import numpy as np
a=np.array([5,6,9])
print(a[0])
print(a[1])
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.shape)


5
6
2
8
int64
6
(3, 2)


In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(a.itemsize)
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
print(a)

8
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [ ]:
a=np.zeros((3,4))
print(a)
a=np.ones((3,4))
print(a)
l=range(5)
print(l)
a=np.arange(1,5)
print(a)
a=np.arange(1,5,2)
print(a)
a=np.linspace(1,5,10)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
range(0, 5)
[1 2 3 4]
[1 3]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
a=a.reshape(2,3)
print(a)
a=a.ravel()
print(a)

(3, 2)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))


[[1 2]
 [3 4]
 [5 6]]
1
6
21
[ 9 12]
[ 3  7 11]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
1.707825127659933


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


##Slicing /Stacking and Indexing with Boolean Array

In [ ]:
import numpy as np
n =[6,7,8]
print(n[0:2])
print(n[-1])
a=np.array([6,7,8])
print(a[0:2])
print(a[-1])

[6, 7]
8
[6 7]
8


In [ ]:
a =np.array([[6,7,8],[1,2,3],[9,3,2]])
print(a)
print(a[1,2])
print(a[0:2,2])
print(a[-1])
print(a[-1,0:2])
print(a[ : ,1:3])




[[6 7 8]
 [1 2 3]
 [9 3 2]]
3
[8 3]
[9 3 2]
[9 3]
[[7 8]
 [2 3]
 [3 2]]


In [ ]:
a =np.array([[6,7,8],[1,2,3],[9,3,2]])
for row in a:
  print(row)
for cell in a.flat:
  print(cell)

[6 7 8]
[1 2 3]
[9 3 2]
6
7
8
1
2
3
9
3
2


In [ ]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [ ]:
a=np.arange(30).reshape(2,15)
print(a)
result=(np.hsplit(a,3))
print(result[0])
print(result[1])
print(result[2])
result=(np.vsplit(a,2))
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [ ]:
a=np.arange(12).reshape(3,4)
print(a)
b=a>4
print(b)
print(a[b])
a[b]=-1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


##**Iterate** Numpy Array using nditer

In [ ]:
a=np.arange(12).reshape(3,4)
print(a)
for row in a:
  for cell in row:
    print(cell)
for cell in a.flatten():
  print(cell)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a,order='C'):
  print(x)


0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a,order='F'):
  print(x)
for x in np.nditer(a,order='F',flags=['external_loop']):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
for x in np.nditer(a,op_flags=['readwrite']):
  x[...]=x*x
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
b=np.arange(3,15,4).reshape(3,1)
print(b)
for x,y in np.nditer([a,b]):
  print(x,y)

[[ 3]
 [ 7]
 [11]]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
